
# Problem 1
import math 

# make math.pi as pi
pi = math.pi

# variables
rho = 860 # [kg/m^3] - density of lubricant
c_p = 2000 # [J/kg/K] - specific heat capacity of lubricant
t_q = 0.25 # [Nm] - torque
c = 0.001 # [m] - thickness of lubricant
omega = 240 # [rpm] - angular velocity
d_i = 0.1 # [m] - inner diameter of the barrel
b = 0.12 # [m] - length of the barrel
delta_T = 3 # [K] - temperature rise of the lubricant

# 1 - lubricant viscocity
# Eq. 6.3:
# t_q = 4* pi**2 *eta_0 * r**3 * b * N_a / c
# rearranging the equation to solve for eta_0
# eta_0 = t_q*c / (4*pi**2 * r**3 * b * N_a)
r = d_i/2
N_a = omega/60

eta_0 = t_q*c / (4* pi **2 * r**3 * b * N_a)

print(f"The lubricant viscocity is: {eta_0:.3f} N.s/m^2")

# 2 - Flow rate in the viscometer

# assuming linear flow profile
A = b * c   # [m^2] - cross-sectional area of the barrel
v = 2 * pi * N_a * r # [m/s] - velocity of the lubricant
Q = 1/2 * A * v # [m^3/s] - flow rate of the lubricant
m_dot = rho * Q # [kg/s] - mass flow rate of the lubricant

print(f"The flow rate in the viscometer is: {Q:.3f} m^3/s")

# 3 - Frictional heat rate
Q_dot = t_q * N_a * 2 * pi # [W] - frictional heat rate

print(f"The frictional heat rate is: {Q_dot:.3f} W")

# 4 - Temperature rise of the lubricant 

m = A * 2 * pi * r * rho # [kg] - mass of the lubricant
delta_t = c_p * m * delta_T / Q_dot # [s] - time taken for the temperature rise

print(f"The time taken for the temperature rise is: {delta_t:.3f} s")

# 5 - exptected phenomenon

# The temperature will continue to increase, as long as there is no other heat transfer mechanism to remove the heat generated by the friction.

print("stop")

